;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	Buffer-menu-delete
	backward-sexp
	c-beginning-of-defun
	c-beginning-of-statement
	c-electric-brace
	c-electric-colon
	c-electric-delete-forward
	c-electric-paren
	c-electric-pound
	c-electric-semi&comma
	c-electric-slash
	c-electric-star
	c-end-of-defun
	c-end-of-statement
	c-indent-line-or-region
	counsel-yank-pop
	dired-undo
	downcase-region
	electric-newline-and-maybe-indent
	end-of-buffer
	eval-and-replace
	forward-sexp
	goto-line
	indent-for-tab-command
	indent-region
	kill-region
	mark-sexp
	open-line-and-indent
	open-line-newline
	org-delete-char
	org-force-self-insert
	org-kill-line
	org-self-insert-command
	undo-redo
	up-list
	upcase-region
	wdired--self-insert
	))

(setq mc/cmds-to-run-once
      '(
	counsel-M-x
	handle-switch-frame
	helpful-key
	swiper-isearch
	wdired-finish-edit
	))
